### ISSUE TITLE
Catch PermissionError on scapy

### ISSUE THREAD

**Issue by Nekmo** [Nekmo/amazon-dash#11]
```
/home/nekmo/.virtualenvs/amazon-dash/bin/python /home/nekmo/Workspace/amazon-dash/scripts/amazon-dash --config amazon-dash.yml --debug run
Traceback (most recent call last):
  File "/home/nekmo/Workspace/amazon-dash/scripts/amazon-dash", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nekmo/Workspace/amazon-dash/amazon_dash/management.py", line 103, in execute_from_command_line
    execute_args(args)
  File "/home/nekmo/Workspace/amazon-dash/amazon_dash/management.py", line 65, in execute_args
    Listener(args.config).run(root_allowed=args.root_allowed)
  File "/home/nekmo/Workspace/amazon-dash/amazon_dash/listener.py", line 97, in run
    scan(self.on_push, lambda d: d.src.lower() in self.devices)
  File "/home/nekmo/Workspace/amazon-dash/amazon_dash/scan.py", line 8, in scan
    sniff(prn=fn, store=0, filter="udp", lfilter=lfilter)
  File "/home/nekmo/.virtualenvs/amazon-dash/lib/python3.6/site-packages/scapy/sendrecv.py", line 572, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/home/nekmo/.virtualenvs/amazon-dash/lib/python3.6/site-packages/scapy/arch/linux.py", line 468, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib64/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted

Process finished with exit code 1
```

**Comment by Nekmo** [comment]
```
/home/nekmo/.virtualenvs/amazon-dash/bin/python /home/nekmo/Workspace/amazon-dash/scripts/amazon-dash --config amazon-dash.yml --debug run
[Error] Amazon Dash Exception:
This program needs permission to open raw sockets on your system. The easy way to run this program is to use root. To use a normal user, consult the documentation.
```
