### ISSUE TITLE
Tried to install it on 4 different systems. no success

### ISSUE THREAD

**Issue by nepo4711** [Nekmo/amazon-dash#115]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Guideline for bug reports
You can delete this section if your report is not a bug

* amazon-dash version: 1.3.2
* Python version: 2.7.13 and 2.7.9 and others
* Pip & Setuptools version: pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7) 
setuptools 33.1.1 from /usr/lib/python2.7/dist-packages (Python 2.7)
* Operating System: Raspian Stretch

How to get your version:
```
amazon-dash --version
python --version
pip --version
easy_install --version
```

- [ ] The `pip install` or `setup install` command has been completed without errors
- [ ] The `python -m amazon_dash.install` command has been completed without errors
- [ ] The `amazon-dash discovery` command works without errors
- [ ] I have created/edited the configuration file
- [ ] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

I installed amazon-dash on 4 different raspberry pi but I get the same errormessage everytime. (A week ago I installed it without problems).

pi@raspberrypi:~ $ sudo amazon-dash discovery
Welcome to Amazon-dash v1.3.2 using Python 2.7.13
The discovery command lists the devices that are connected in your network. Each device will only be listed once. After executing this command wait approximately 10 seconds before pressing the Amazon Dash button. After pressing the button, the Mac address of the button will immediately appear on the screen. Remember the address to be able to create the configuration file.
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 6, in <module>
    catch(cli)()
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/exceptions.py", line 91, in wrap
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 127, in discovery
    discover(interface)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/discovery.py", line 98, in discover
    scan_devices(discovery_print, lfilter=lambda d: d.src not in mac_id_list, iface=interface)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/scan.py", line 27, in scan_devices
    lfilter=lfilter, iface=iface)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 836, in sniff
    *arg, **karg)] = iface
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 454, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 140, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/common.py", line 126, in compile_filter
    raise Scapy_Exception("tcpdump is not available. Cannot use filter !")
scapy.error.Scapy_Exception: tcpdump is not available. Cannot use filter !
pi@raspberrypi:~ $

**Comment by narfel** [comment]
Install tcpdump and then check if scapy is correctly installed by running it on the cli

**Comment by XzavierDunn** [comment]
I had the same issue and when I try to install tcpdump it says it can't find a version to satisfie the requirement tcpdump.

**Comment by Nekmo** [comment]
> I had the same issue and when I try to install tcpdump it says it can't find a version to satisfy the requirement tcpdump.

Paste the error @XzavierDunn

**Comment by jacobmartin03** [comment]
Had the same issue, and simply installing tcpdump with `apt install tcpdump` solved it all

**Comment by Nekmo** [comment]
Closed due to inactivity.
