### ISSUE TITLE
Python2 unsupported

### ISSUE THREAD

**Issue by Nekmo** [Nekmo/amazon-dash#3]
```
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 95, in execute_from_command_line
    Listener(args.config).run(root_allowed=args.root_allowed)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/listener.py", line 75, in __init__
    self.config = Config(config_path)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/config.py", line 39, in __init__
    super().__init__(**kwargs)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by Nekmo** [comment]
Resolved in 0.2.2
