### ISSUE TITLE
running systemctl

### ISSUE THREAD

**Issue by four2six** [Nekmo/amazon-dash#46]
amazon-dash version: v1.0.2
Python version: 2.7.3.
Operating System: Raspbian

```
$ sudo systemctl start amazon-dash
```

gives me

```
Failed to start amazon-dash.service: Unknown unit: amazon-dash.service
```

running it with `sudo amazon-dash run` works

i would appreciate any ideas where to start looking. i tried going my usual way with python scripts and install a crobtab, but i failed miserably.

**Comment by Nekmo** [comment]
Hello, have you executed the second step of the installation?

```
$ sudo python -m amazon_dash.install
```

**Comment by four2six** [comment]
as far as i remember i did.

when i do it now it gives me

```
sudo python -m amazon_dash.install
Executing all install scripts for Amazon-Dash
[Already installed] /etc/amazon-dash.yml already exists
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/install/__main__.py", line 3, in <module>
    catch(cli)()
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/install/__init__.py", line 35, in wrap
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/install/__init__.py", line 140, in all
    has_service = has_service or (service().install() and
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/install/__init__.py", line 59, in install
    self.is_installable()
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/install/__init__.py", line 95, in is_installable
    if not get_pid('systemd') or not get_systemd_services_path():
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/install/__init__.py", line 21, in get_pid
    return check_output(["pidof", name])
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pidof', 'systemd']' returned non-zero exit status 1
```

**Comment by Nekmo** [comment]
Is pidof available on your system? Try running "pidof" in a terminal.

**Comment by four2six** [comment]
no pidof

does ps help?

```
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.3   3352  1648 ?        Ss   04:00   0:01 init [2]  
root         2  0.0  0.0      0     0 ?        S    04:00   0:00 [kthreadd]
root         4  0.0  0.0      0     0 ?        I<   04:00   0:00 [kworker/0:0H]
root         6  0.0  0.0      0     0 ?        I<   04:00   0:00 [mm_percpu_wq]
root         7  0.0  0.0      0     0 ?        S    04:00   0:08 [ksoftirqd/0]
root         8  0.0  0.0      0     0 ?        S    04:00   0:00 [kdevtmpfs]
root         9  0.0  0.0      0     0 ?        I<   04:00   0:00 [netns]
root        11  0.0  0.0      0     0 ?        S    04:00   0:00 [khungtaskd]
root        12  0.0  0.0      0     0 ?        S    04:00   0:00 [oom_reaper]
root        13  0.0  0.0      0     0 ?        I<   04:00   0:00 [writeback]
root        14  0.0  0.0      0     0 ?        S    04:00   0:00 [kcompactd0]
root        15  0.0  0.0      0     0 ?        I<   04:00   0:00 [crypto]
root        16  0.0  0.0      0     0 ?        I<   04:00   0:00 [kblockd]
root        17  0.0  0.0      0     0 ?        I<   04:00   0:00 [watchdogd]
root        18  0.0  0.0      0     0 ?        I<   04:00   0:00 [rpciod]
root        19  0.0  0.0      0     0 ?        I<   04:00   0:00 [xprtiod]
root        22  0.0  0.0      0     0 ?        S    04:00   0:00 [kswapd0]
root        23  0.0  0.0      0     0 ?        I<   04:00   0:00 [nfsiod]
root        33  0.0  0.0      0     0 ?        I<   04:00   0:00 [kthrotld]
root        34  0.0  0.0      0     0 ?        I<   04:00   0:00 [iscsi_eh]
root        35  0.0  0.0      0     0 ?        I<   04:00   0:00 [dwc_otg]
root        36  0.0  0.0      0     0 ?        I<   04:00   0:00 [DWC Notificatio]
root        37  0.0  0.0      0     0 ?        S<   04:00   0:00 [vchiq-slot/0]
root        38  0.0  0.0      0     0 ?        S<   04:00   0:00 [vchiq-recy/0]
root        39  0.0  0.0      0     0 ?        S<   04:00   0:00 [vchiq-sync/0]
root        40  0.0  0.0      0     0 ?        S    04:00   0:00 [vchiq-keep/0]
root        42  0.0  0.0      0     0 ?        S    04:00   0:06 [mmcqd/0]
root        44  0.0  0.0      0     0 ?        S    04:00   0:01 [jbd2/mmcblk0p2-]
root        45  0.0  0.0      0     0 ?        I<   04:00   0:00 [ext4-rsv-conver]
root        46  0.0  0.0      0     0 ?        I<   04:00   0:00 [kworker/0:1H]
root       197  0.0  0.5  13952  2816 ?        Ss   04:00   0:02 /lib/systemd/systemd-udevd --daemon
root       244  8.1  0.0      0     0 ?        S    04:00  24:28 [w1_bus_master1]
root       245  0.0  0.0      0     0 ?        S    04:00   0:00 [spi0]
root      2060  0.0  0.2   1876  1208 ?        S    04:03   0:15 /usr/sbin/ifplugd -i eth0 -q -f -u0 -d10 -w -I
root      2074  0.0  0.2   1876  1192 ?        S    04:03   0:03 /usr/sbin/ifplugd -i lo -q -f -u0 -d10 -w -I
root      2173  0.0  0.5   5960  2812 ?        S    04:03   0:00 /sbin/cgmanager --daemon -m name=systemd
root      2294  0.0  0.5  30456  2760 ?        Sl   04:03   0:04 /usr/sbin/rsyslogd -c5
root      2326  0.0  0.7  10988  3708 ?        Ss   04:03   0:00 /usr/sbin/nmbd -D
root      2328  0.0  1.8  26576  9040 ?        Ss   04:03   0:00 /usr/sbin/smbd -D
root      2347  0.0  0.6  27092  3040 ?        S    04:03   0:00 /usr/sbin/smbd -D
nobody    2363  0.0  0.5   5284  2468 ?        Ss   04:03   0:00 /usr/sbin/thd --daemon --triggers /etc/triggerhappy/triggers.d/ --socket /var/run/thd.socket --pidfile /var/run/thd.pid --user nobody /dev/input/
root      2411  0.0  0.4   5288  2088 ?        Ss   04:03   0:00 /usr/sbin/cron
root      2415  0.0  0.5   6708  2540 ?        S    04:03   0:00 /usr/sbin/CRON
root      2425  0.0  0.2   1884  1100 ?        Ss   04:03   0:00 /bin/sh -c python /home/pi/pythonscripts/arp_to_ifttt.py
root      2426  0.1  1.7  12048  8700 ?        S    04:03   0:22 python /home/pi/pythonscripts/arp_to_ifttt.py
104       2446  0.0  0.5   6504  2708 ?        Ss   04:03   0:00 /usr/bin/dbus-daemon --system
root      2471  1.3  3.3 225820 16716 ?        Ssl  04:03   4:01 /home/pi/domoticz/domoticz -daemon -www 8080 -sslwww 443 -log /tmp/domoticz.txt
root      2524  0.3  1.6  45980  8280 ?        Sl   04:03   0:56 /usr/bin/python /usr/bin/fail2ban-server -b -s /var/run/fail2ban/fail2ban.sock
root      2526  0.0  0.5   4248  2720 ?        S    04:03   0:08 /usr/lib/gamin/gam_server
106       2570  0.1  0.7   5596  3804 ?        S    04:03   0:34 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
root      2600  0.0  0.8   7368  4260 ?        S    04:03   0:00 /lib/systemd/systemd-logind
pi        2619  0.2 11.2 139552 55404 ?        Sl   04:03   0:45 node-red                                                                                              
ntp       2650  0.0  0.6   7876  2964 ?        Ssl  04:03   0:04 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 102:104
110       2702  0.2  1.0  12184  4956 ?        S    04:04   0:41 /usr/sbin/snmpd -Lsd -Lf /dev/null -u Debian-snmp -g Debian-snmp -I -smux mteTrigger mteTriggerConf -p /run/snmpd.pid
root      2740  0.0  0.5   7944  2944 ?        Ss   04:04   0:00 /usr/sbin/sshd
avahi     2800  0.0  0.6   6516  3232 ?        S    04:04   0:13 avahi-daemon: running [raspberrypi.local]
avahi     2802  0.0  0.3   6384  1604 ?        S    04:04   0:00 avahi-daemon: chroot helper
root      2869  0.0  0.3   4180  1816 tty1     Ss+  04:04   0:00 /sbin/getty --noclear 38400 tty1
root      2870  0.0  0.3   4180  1700 tty2     Ss+  04:04   0:00 /sbin/getty 38400 tty2
root      2871  0.0  0.3   4180  1868 tty3     Ss+  04:04   0:00 /sbin/getty 38400 tty3
root      2872  0.0  0.3   4180  1784 tty4     Ss+  04:04   0:00 /sbin/getty 38400 tty4
root      2873  0.0  0.3   4180  1844 tty5     Ss+  04:04   0:00 /sbin/getty 38400 tty5
root      2875  0.0  0.3   4180  1856 tty6     Ss+  04:04   0:00 /sbin/getty 38400 tty6
root      9139  0.0  0.0      0     0 ?        I    08:09   0:00 [kworker/u2:2]
root      9728  0.0  0.0      0     0 ?        I    08:34   0:00 [kworker/0:1]
root      9772  0.0  0.0      0     0 ?        I    08:36   0:00 [kworker/u2:1]
root     10086  0.0  0.0      0     0 ?        I    08:50   0:00 [kworker/0:0]
root     10210  0.1  0.0      0     0 ?        I    08:55   0:00 [kworker/0:2]
root     10254  0.3  1.0  11900  5108 ?        Ss   08:57   0:00 sshd: pi [priv]  
pi       10272  0.1  0.7  11900  3480 ?        S    08:57   0:00 sshd: pi@pts/0   
pi       10274  1.2  1.3   8828  6764 pts/0    Ss   08:57   0:01 -bash
root     10562  0.7  0.5   6708  2548 ?        S    09:00   0:00 /usr/sbin/CRON
pi       10566  0.0  0.2   1884  1100 ?        Ss   09:00   0:00 /bin/sh -c /usr/bin/python /home/pi/GCal/gcal.py
pi       10567 90.0  2.8  17740 14128 ?        R    09:00   0:03 /usr/bin/python /home/pi/GCal/gcal.py
pi       10575  0.0  0.4   4888  2236 pts/0    R+   09:00   0:00 ps aux
```

**Comment by Nekmo** [comment]
Install pidof in your system.

**Comment by four2six** [comment]
um no
