### ISSUE TITLE
Run command produces "No module named subprocess32" error

### ISSUE THREAD

**Issue by ttonyh** [Nekmo/amazon-dash#54]
* amazon-dash version: 1.0.4
* Python version: 2.7.13
* Operating System: Linux 4.14.34-v7+ #1110 / armv7l (Raspbian Stretch Lite / Raspberry Pi)

### Description
Running the 'run' command or via service produces the error posted below. However, both 'discovery' and 'check-config' commands worked just fine.

### What I Did
Used 'run' command also via the service.

```
Welcome to Amazon-dash v1.0.4 using Python 2.7.13
Listening for events. Amazon-dash will execute the events associated with the registered buttons.
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 6, in <module>
    catch(cli)()
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/exceptions.py", line 91, in wrap
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 99, in run
    from amazon_dash.listener import Listener
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/listener.py", line 6, in <module>
    from amazon_dash.confirmations import get_confirmation
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/confirmations.py", line 5, in <module>
    from amazon_dash._compat import JSONDecodeError
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/_compat.py", line 18, in <module>
    import subprocess32 as subprocess
ImportError: No module named subprocess32
```

**Comment by Nekmo** [comment]
Install subprocess32:

```
$ pip install subprocess32
```

**Comment by Nekmo** [comment]
Closed due to inactivity.
