### ISSUE TITLE
Help instead raise FileNotFoundError when amazon-dash is not available

### ISSUE THREAD

**Issue by Nekmo** [Nekmo/amazon-dash#7]
```
(amazon-dash) [nekmo@homura ~/Workspace/amazon-dash] (master)$ ./scripts/amazon-dash 
Traceback (most recent call last):
  File "./scripts/amazon-dash", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nekmo/Workspace/amazon-dash/amazon_dash/management.py", line 95, in execute_from_command_line
    Listener(args.config).run(root_allowed=args.root_allowed)
  File "/home/nekmo/Workspace/amazon-dash/amazon_dash/listener.py", line 75, in __init__
    self.config = Config(config_path)
  File "/home/nekmo/Workspace/amazon-dash/amazon_dash/config.py", line 40, in __init__
    if (not os.getuid() and not only_root_write(file)) or oth_w_perm(file):
  File "/home/nekmo/Workspace/amazon-dash/amazon_dash/config.py", line 23, in oth_w_perm
    return bitperm(os.stat(file), 'w', 'oth')
FileNotFoundError: [Errno 2] No such file or directory: 'amazon-dash.yml'
```

**Comment by Nekmo** [comment]
```
/home/nekmo/.virtualenvs/amazon-dash/bin/python /home/nekmo/Workspace/amazon-dash/scripts/amazon-dash --config amazon-dash.yml --debug run
[Error] Amazon Dash Exception:
The configuration file was not found on "/home/nekmo/Workspace/amazon-dash/amazon-dash.yml"
```
