### ISSUE TITLE
No module named subprocess32

### ISSUE THREAD

**Issue by mooproxy** [Nekmo/amazon-dash#72]
### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Guideline for bug reports
You can delete this section if your report is not a bug

* amazon-dash version: v1.1.1
* Python version: 2.7.13.
* Pip & Setuptools version: 18.0
* Operating System: Raspbian Stretch Lite 4.14

- [x ] The `pip install` or `setup install` command has been completed without errors
- [ x] The `python -m amazon_dash.install` command has been completed without errors
- [ x] The `amazon-dash discovery` command works without errors
- [ x] I have created/edited the configuration file
- [ ] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

I realise there is another thread with this same issue, however their fix simply did not work for me. In short, download and install seemed to work without issues, I can and have discovered the MAC address of my button and edited the config file as such, however when attempting to run amazon-dash, it throws and error that there is no module named subprocess32.

#### What I Did

root@raspberrypi:/etc# amazon-dash
Welcome to Amazon-dash v1.1.1 using Python 2.7.13
Listening for events. Amazon-dash will execute the events associated with the registered buttons.
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 6, in <module>
    catch(cli)()
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/exceptions.py", line 91, in wrap
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 99, in run
    from amazon_dash.listener import Listener
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/listener.py", line 6, in <module>
    from amazon_dash.confirmations import get_confirmation
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/confirmations.py", line 5, in <module>
    from amazon_dash._compat import JSONDecodeError
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/_compat.py", line 18, in <module>
    import subprocess32 as subprocess
ImportError: No module named subprocess32

**Comment by Nekmo** [comment]
Your setuptools version is too old. Release 18.0 was released on Jun 23 2015. 

Upgrade setuptools:
```
pip install -U setuptools
```

And reinstall amazon-dash
```
pip install -I -U --no-cache-dir amazon-dash
```

**Comment by mooproxy** [comment]
Apologies that I left it ambiguous in my original post. I meant my pip was v18.0. My setuptools is up to date (v40.0.0), though I tried to update to be sure and reinstall amazon-dash and the problem persists.

**Comment by Nekmo** [comment]
Please paste the installation output here (`pip install -I -U --no-cache-dir amazon-dash`). I can't reproduce the error.

```
[nekmo@homura ~]$ mktmpenv -p /usr/bin/python2
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/nekmo/.virtualenvs/tmp-e3a697515d055f4/bin/python2
Also creating executable in /home/nekmo/.virtualenvs/tmp-e3a697515d055f4/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-e3a697515d055f4/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-e3a697515d055f4/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-e3a697515d055f4/bin/preactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-e3a697515d055f4/bin/postactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-e3a697515d055f4/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
```

```
(tmp-e3a697515d055f4) [nekmo@homura ~/.virtualenvs/tmp-e3a697515d055f4]$ pip install -U setuptools pip
Requirement already up-to-date: setuptools in ./lib/python2.7/site-packages (40.0.0)
Requirement already up-to-date: pip in ./lib/python2.7/site-packages (18.0)
(tmp-e3a697515d055f4) [nekmo@homura ~/.virtualenvs/tmp-e3a697515d055f4]$ pip install amazon-dash
Collecting amazon-dash
  Downloading https://files.pythonhosted.org/packages/d8/04/0f445d865e01e8514e7ab023bc48e9a7dc133e2e50ccd46d88db92ff5d9a/amazon-dash-1.1.1.tar.gz
Collecting PyYAML>=3.0 (from amazon-dash)
Collecting jsonschema (from amazon-dash)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting requests (from amazon-dash)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting click (from amazon-dash)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting click-default-group (from amazon-dash)
Collecting scapy (from amazon-dash)
Collecting subprocess32 (from amazon-dash)
Collecting functools32; python_version == "2.7" (from jsonschema->amazon-dash)
Collecting chardet<3.1.0,>=3.0.2 (from requests->amazon-dash)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests->amazon-dash)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->amazon-dash)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->amazon-dash)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Building wheels for collected packages: amazon-dash
  Running setup.py bdist_wheel for amazon-dash ... done
  Stored in directory: /home/nekmo/.cache/pip/wheels/56/be/6f/24701edfcce1c979520151a4e2d8f8ad324b8fcfb96a7d13ec
Successfully built amazon-dash
Installing collected packages: PyYAML, functools32, jsonschema, chardet, urllib3, certifi, idna, requests, click, click-default-group, scapy, subprocess32, amazon-dash
Successfully installed PyYAML-3.13 amazon-dash-1.1.1 certifi-2018.4.16 chardet-3.0.4 click-6.7 click-default-group-1.2 functools32-3.2.3.post2 idna-2.7 jsonschema-2.6.0 requests-2.19.1 scapy-2.4.0 subprocess32-3.5.2 urllib3-1.23
```

```
(tmp-e3a697515d055f4) [nekmo@homura ~/.virtualenvs/tmp-e3a697515d055f4]$ sudo amazon-dash --debug run --config /etc/amazon-dash.yml 
Welcome to Amazon-dash v1.1.1 using Python 2.7.15
Listening for events. Amazon-dash will execute the events associated with the registered buttons.
```

**Comment by mooproxy** [comment]
Fair enough, I've never really used python before so can't really eliminate the possibility I've done something stupid here. Upon running your reinstall command:

```
root@raspberrypi:/home/pi# pip install -I -U --no-cache-dir amazon-dash
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting amazon-dash
  Downloading https://www.piwheels.org/simple/amazon-dash/amazon_dash-1.1.1-py2.py3-none-any.whl
Collecting click-default-group (from amazon-dash)
  Downloading https://files.pythonhosted.org/packages/86/3e/389d8bbe3033613b17ce4136dbcf3e69c785c9c54d08f3adb95336b52040/click-default-group-1.2.tar.gz
Collecting click (from amazon-dash)
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 1.2MB/s
Collecting requests (from amazon-dash)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 1.9MB/s
Collecting jsonschema (from amazon-dash)
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting scapy>=2.4.0 (from amazon-dash)
  Downloading https://files.pythonhosted.org/packages/68/01/b9943984447e7ea6f8948e90c1729b78161c2bb3eef908430638ec3f7296/scapy-2.4.0.tar.gz (3.1MB)
    100% |████████████████████████████████| 3.1MB 2.1MB/s
Collecting PyYAML>=3.0 (from amazon-dash)
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |████████████████████████████████| 276kB 2.1MB/s
Collecting idna<2.8,>=2.5 (from requests->amazon-dash)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 1.8MB/s
Collecting urllib3<1.24,>=1.21.1 (from requests->amazon-dash)
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 2.2MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests->amazon-dash)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 2.1MB/s
Collecting certifi>=2017.4.17 (from requests->amazon-dash)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 2.1MB/s
Collecting functools32; python_version == "2.7" (from jsonschema->amazon-dash)
  Downloading https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
Installing collected packages: click, click-default-group, idna, urllib3, chardet, certifi, requests, functools32, jsonschema, scapy, PyYAML, amazon-dash
  Running setup.py install for click-default-group ... done
  Running setup.py install for functools32 ... done
  Running setup.py install for scapy ... done
  Running setup.py install for PyYAML ... done
Successfully installed PyYAML-3.13 amazon-dash-1.1.1 certifi-2018.4.16 chardet-3.0.4 click-6.7 click-default-group-1.2 functools32-3.2.3.post2 idna-2.7 jsonschema-2.6.0 requests-2.19.1 scapy-2.4.0 urllib3-1.23
```

And running the amazon-dash command:

```
root@raspberrypi:/home/pi# amazon-dash
Welcome to Amazon-dash v1.1.1 using Python 2.7.13
Listening for events. Amazon-dash will execute the events associated with the registered buttons.
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 6, in <module>
    catch(cli)()
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/exceptions.py", line 91, in wrap
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 99, in run
    from amazon_dash.listener import Listener
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/listener.py", line 6, in <module>
    from amazon_dash.confirmations import get_confirmation
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/confirmations.py", line 5, in <module>
    from amazon_dash._compat import JSONDecodeError
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/_compat.py", line 18, in <module>
    import subprocess32 as subprocess
ImportError: No module named subprocess32
```

**Comment by Nekmo** [comment]
I think the problem is in the wheel package. The wheel packages give a lot of problems.

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
```

I'm investigating the problem.

**Comment by Nekmo** [comment]
The problem is in piwheels. I have opened a ticket requesting support.

https://github.com/bennuttall/piwheels/issues/83

Meanwhile you can install amazon-dash using a valid installer:

```
pip install  -I -U --no-cache-dir https://files.pythonhosted.org/packages/d8/04/0f445d865e01e8514e7ab023bc48e9a7dc133e2e50ccd46d88db92ff5d9a/amazon-dash-1.1.1.tar.gz
```

**Comment by mooproxy** [comment]
You're right, my mistake. Thank you for your help.

**Comment by mooproxy** [comment]
Apologies about the closing and reopening - I encountered another issue.

Amazon-dash doesn't seem to be running on startup. Manually entering the comment and pressing the button works just fine but startup doesn't. I just want to check whether the specific installation command you gave me or any other quirks of this specific issue may be causing this.

**Comment by Nekmo** [comment]
You are welcome :) I hope to be able to solve the problem soon with the piwheels team.

**Comment by Nekmo** [comment]
@mooproxy  Check systemd service:

```
systemctl status amazon-dash
```

**Comment by mooproxy** [comment]
Well, it does seem to be inactive. If it helps, whenever I run the command manually it always looks for the yml file in the directory I'm running the command out of rather than being at /etc/amazon-dash.yml, so when running the command I've had to run it out of there. Just in case that's causing issues with it breaking from not being able to find the right file.

```
pi@raspberrypi:~ $ systemctl status amazon-dash
● amazon-dash.service - Amazon Dash service
   Loaded: loaded (/lib/systemd/system/amazon-dash.service; disabled; vendor pre
   Active: inactive (dead)
```

**Comment by Nekmo** [comment]
You can enable amazon-dash service:

```
systemctl enable amazon-dash
```

This starts amazon-dash always on startup.

**Comment by mooproxy** [comment]
That fixed it. Thanks a lot for all your help.
