### ISSUE TITLE
"sudo" is not available for root user in docker container

### ISSUE THREAD

**Issue by vergissberlin** [Nekmo/amazon-dash#91]
**Hi!**

and thank you for publishing your code!
I tried the application to get started with docker an get following exception:
```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/amazon_dash/listener.py", line 84, in execute
    result = self.execute_instance.execute(root_allowed)
  File "/usr/local/lib/python3.7/site-packages/amazon_dash/execute.py", line 167, in execute
    output = execute_cmd(cmd, self.data.get('cwd'))
  File "/usr/local/lib/python3.7/site-packages/amazon_dash/execute.py", line 58, in execute_cmd
    p = subprocess.Popen(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo': 'sudo'
```
I think the last message ``No such file or directory: 'sudo': 'sudo'``is the key. Everytime you log in or running a docker image, you are the user _root_ inside of the running container. An _root_ doesn't know the command ``sudo``:

https://github.com/Nekmo/amazon-dash/blob/96e5493f1ea61a4bb014bd52f367985cf987f031/amazon_dash/execute.py#L48

**My two different proposals:**
1. Create and use a new user und the *Dockerfile*
2. Test if sudo exist on cli before run it in the python script.

kind regards,
André

**Comment by Nekmo** [comment]
Hi @vergissberlin. It seems that sudo is not installed in docker, but this has not given issues before. I will investigate this issue. Thanks!

**Comment by bertobert** [comment]
The docker default user is root - so no need to use sudo. 
The next issue you will run into is the usage of bash as the shell - this is also not installed in the provided DOCKERFILE.
On my local machine I patched the execute.py by removing the sudo in the command and used 'sh' instead of 'bash'.
But this is just a hack - for really fixing this you would first want to check the user running the script and second check whether you are missing something from sh which only bash can provide.

**Comment by Nekmo** [comment]
Confirmed.

```
(amazon-dash) [nekmo@homura ~/Workspace/amazon-dash] (develop)$ docker run -it --network=host -v $PWD/amazon-dash.yml:/config/amazon-dash.yml nekmo/amazon-dash:latest amazon-dash --deg run --config /config/amazon-dash.yml --root-allowed --ignore-perms
Welcome to Amazon-dash v1.2.0a1 using Python 3.7.0
Listening for events. Amazon-dash will execute the events associated with the registered buttons.
2018-09-25 18:46:35,655 - amazon-dash - DEBUG   - Lounge device executed (mac 44:65:0d:16:8b:b8)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/amazon_dash/listener.py", line 84, in execute
    result = self.execute_instance.execute(root_allowed)
  File "/usr/local/lib/python3.7/site-packages/amazon_dash/execute.py", line 167, in execute
    output = execute_cmd(cmd, self.data.get('cwd'))
  File "/usr/local/lib/python3.7/site-packages/amazon_dash/execute.py", line 58, in execute_cmd
    p = subprocess.Popen(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo': 'sudo'
```
